filebeat.inputs:
- type: log
  enabled: true
  paths:
    - data/test.log

filebeat.config.modules:
  path: /opt/modules.d/*.yml
  reload.enabled: false


output.logstash:
  hosts: ["localhost:5044"]
